import asyncio
import os
import textwrap
from typing import List, Optional
from openai import OpenAI

# Import the OpenEnv async client and action model
try:
    from client import OpenenvSreClient  # generated by openenv init
    from models import SREAction, SREObservation
except ImportError:
    raise ImportError("Run from project root: python inference.py")

IMAGE_NAME = os.getenv("IMAGE_NAME")
API_KEY = os.getenv("HF_TOKEN") or os.getenv("API_KEY")
API_BASE_URL = os.getenv("API_BASE_URL", "https://router.huggingface.co/v1")
MODEL_NAME = os.getenv("MODEL_NAME", "Qwen/Qwen2.5-72B-Instruct")
BENCHMARK = "openenv_sre"
TEMPERATURE = 0.1
MAX_TOKENS = 150
SUCCESS_SCORE_THRESHOLD = 0.5

TASKS = [
    {"name": "easy",   "max_steps": 10},
    {"name": "medium", "max_steps": 20},
    {"name": "hard",   "max_steps": 35},
]

SYSTEM_PROMPT = textwrap.dedent("""
You are an on-call SRE agent responding to a production incident.
You observe alerts and metrics from a 6-service microservice system:
  gateway, api, db, cache, queue, worker

A service is HEALTHY when: latency_ms < 300 AND error_rate < 0.05 AND cpu_pct < 80.
Your goal: restore ALL services to healthy state.

Available actions:
  RESTART_SERVICE     — params: service
  ROLLBACK_DEPLOY     — params: service (use when error_rate > 0.30)
  SCALE_UP            — params: service, replicas
  SCALE_DOWN          — params: service, replicas
  DRAIN_QUEUE         — params: queue
  SHIFT_TRAFFIC       — params: from_service, to_service, pct
  TOGGLE_FEATURE_FLAG — params: flag, value (use value=false to disable)
  CLEAR_CACHE         — params: service
  OBSERVE             — params: service (no state change, use to inspect)

Respond ONLY with a single valid JSON object. Raw JSON, no markdown, no explanation:
{
  "action_type": "ACTION_NAME",
  "service": "service_name or null",
  "replicas": null,
  "queue": null,
  "from_service": null,
  "to_service": null,
  "pct": null,
  "flag": null,
  "value": null
}
""").strip()


# ── logging helpers (exact format required by hackathon) ─────────────────────

def log_start(task: str, env: str, model: str) -> None:
    print(f"[START] task={task} env={env} model={model}", flush=True)


def log_step(step: int, action: str, reward: float, done: bool, error: Optional[str]) -> None:
    error_val = error if error else "null"
    done_val = str(done).lower()
    print(
        f"[STEP] step={step} action={action} reward={reward:.2f} done={done_val} error={error_val}",
        flush=True,
    )


def log_end(success: bool, steps: int, score: float, rewards: List[float]) -> None:
    rewards_str = ",".join(f"{r:.2f}" for r in rewards)
    print(
        f"[END] success={str(success).lower()} steps={steps} score={score:.3f} rewards={rewards_str}",
        flush=True,
    )


# ── model call ───────────────────────────────────────────────────────────────

def get_action(client: OpenAI, observation_json: str, step: int) -> SREAction:
    prompt = f"Step {step}. Current observation:\n{observation_json}\nChoose the best single action. Reply JSON only."
    try:
        completion = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=TEMPERATURE,
            max_tokens=MAX_TOKENS,
            stream=False,
        )
        raw = (completion.choices[0].message.content or "").strip()
        if "```" in raw:
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        return SREAction.model_validate_json(raw)
    except Exception as e:
        print(f"[DEBUG] Model parse error: {e}", flush=True)
        return SREAction(action_type="OBSERVE", service="api")


# ── episode runner ───────────────────────────────────────────────────────────

async def run_episode(client: OpenAI, task_name: str, max_steps: int) -> None:
    log_start(task=task_name, env=BENCHMARK, model=MODEL_NAME)

    rewards: List[float] = []
    steps_taken = 0
    score = 0.0
    success = False

    # Connect to running Docker container via WebSocket
    env = await OpenenvSreClient.from_docker_image(IMAGE_NAME)

    try:
        result = await env.reset(task=task_name, seed=42)
        obs = result.observation

        for step in range(1, max_steps + 1):
            if result.done:
                break

            action = get_action(client, obs.model_dump_json(indent=2), step)
            result = await env.step(action)
            obs = result.observation

            reward = result.reward or 0.0
            done = result.done
            error = getattr(obs, "last_action_result", None)
            error = error if error not in ("success", "no_effect", "reset", None) else None

            rewards.append(reward)
            steps_taken = step

            log_step(
                step=step,
                action=action.action_type,
                reward=reward,
                done=done,
                error=error,
            )

            if done:
                break

        # Get final score from metadata
        score = 0.0
        if result.done and hasattr(result, "metadata") and result.metadata:
            score = result.metadata.get("episode_score", 0.0)
        score = min(max(float(score), 0.0), 1.0)
        success = score >= SUCCESS_SCORE_THRESHOLD

    finally:
        try:
            await env.close()
        except Exception as e:
            print(f"[DEBUG] env.close() error: {e}", flush=True)
        log_end(success=success, steps=steps_taken, score=score, rewards=rewards)


# ── main ─────────────────────────────────────────────────────────────────────

async def main() -> None:
    if not API_KEY:
        print("[ERROR] HF_TOKEN or API_KEY environment variable not set.", flush=True)
        return

    client = OpenAI(base_url=API_BASE_URL, api_key=API_KEY)

    for task in TASKS:
        await run_episode(client, task["name"], task["max_steps"])


if __name__ == "__main__":
    asyncio.run(main())
